[package]
name = "yew-tutorial"
version = "0.1.0"
authors = ["Andrew Maksymowsky <andyj010@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"
